site_name: Pylon Docs
site_description: Documentation for the Minecraft Pylon plugin
site_author: PylonMC
repo_url: https://github.com/pylonmc/pylon-docs

theme:
  name: material
  logo: img/favicon.png
  favicon: img/favicon.png
  palette:
    scheme: slate
    primary: custom
    accent: cyan
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - content.tabs.link
  icon:
    repo: simple/github

extra:
  social:
    - icon: simple/discord
      link: https://discord.gg/4tMAnBAacW
    - icon: simple/github
      link: https://github.com/pylonmc

extra_css:
  - style.css

nav:
  - Home:
    - What is Pylon?: index.md
    - Installing Pylon: home/installing-pylon.md
    - List of addons: home/list-of-addons.md
    - Commands & permissions: home/commands-and-permissions.md
    - Documentation progress: progress.md
  - Creating addons:
    - Tutorial 0 - Getting started: creating-addons/tutorial-0.md
    - Tutorial 1 - Your first item: creating-addons/tutorial-1.md
    - Tutorial 2 - Customising items: creating-addons/tutorial-2.md
    - Tutorial 3 - Lore: creating-addons/tutorial-3.md
    - Tutorial 4 - Saving data to items: creating-addons/tutorial-4.md
  - Documentation:
    - Overview: documentation/overview.md
    - Reference:
      - Blocks:
        - Creating new blocks: documentation/reference/blocks/creating-new-blocks.md
        - Block interfaces: documentation/reference/blocks/interfaces.md
        - Persistent data: documentation/reference/blocks/persistent-data.md
        - WAILA: documentation/reference/blocks/waila.md
        - Settings: documentation/reference/blocks/settings.md
      - Multiblocks:
        - Simple multiblocks: documentation/reference/multiblocks/simple-multiblocks.md
        - Multiblock state: documentation/reference/multiblocks/multiblock-state.md
        - Interacting with components: documentation/reference/multiblocks/interacting-with-components.md
        - Custom multiblocks: documentation/reference/multiblocks/custom-multiblocks.md
      - Language system:
        - Tags: documentation/reference/language-system/tags.md
    - Internals:
      - Data-oriented interfaces: documentation/internals/data-oriented-interfaces.md
      - Fluids: documentation/internals/fluids.md
      - Cargo: documentation/internals/cargo.md
      - Internationalization: documentation/internals/i18n.md
    - Contributing:
      - Getting started: documentation/contributing/getting-started.md
      - The Pylon Master Project: documentation/contributing/master-project.md
      - Contributing to docs: documentation/contributing/contributing-to-docs.md

markdown_extensions:
  - def_list
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
      guess_lang: false
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - open-in-new-tab
  - i18n:
      docs_structure: folder
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
